spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~jpabookshop;MVC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
#   로그에 출력 => 실무는 이거 써야함
    org.hibernate.SQL: debug